### ISSUE TITLE
[Webpack] cssRules does not apply to .scss files imported from a .html file.

### ISSUE THREAD

**Issue by graycrow** [aurelia/cli#1152]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
13.0.1

* **NPM Version:**
6.12.1

* **Browser:**
all
* **Language:**
TypeScript 3.6.4

* **Loader/bundler:**
Webpack

**Current behavior:**
If I import SASS styles from the model (.ts), they are processed by the PostCss loader, autorefixer rules are applied, etc. If the same file is imported from the view (.html), the Css loader options are not applied.

* **What is the expected behavior?**
This line:
https://github.com/aurelia/cli/blob/17afc51a93e5b2c50a759729e4b6a55fd138e9c9/skeleton/webpack/webpack.config.js#L277

probably should be replaced by something like this:
`use: [...cssRules, ...sassRules],`

* **What is the motivation / use case for changing the behavior?**
I'd like all styles to be handled equally. The appearance of the page should not depend on the import method.

**Comment by 3cp** [comment]
This is actually by design.

Importing css file is not a standard feature out JS. Webpack uses style-loader to inject css into HTML head at runtime.

That's what happens when you import css from js file.

When you require css resource from html file, Aurelia actually handle the css injection by itself. This is implemented as a feature inside Aurelia framework, it doesn't need the help from any bundler. It's something like a bulit-in style-loader.

That's why there is two different css config inside webpack config. One for css from js file, one for css from html file.

**Comment by 3cp** [comment]
Sorry, I missed your point. Correct, it should be cssRules. PR welcome!

**Comment by 3cp** [comment]
@Sayan751 I thought we cleaned up css config. Can you review all of css config?
