### ISSUE TITLE
Latest enquirer release seems to break 'au build' with 'SyntaxError: Unexpected token ='

### ISSUE THREAD

**Issue by AshWhitear** [aurelia/cli#1203]
**I'm submitting a bug report**

* **Library Version:**
3.0.1

**Please tell us about your environment:**
* **Operating System:**
Mac OS & Windows Server 2022

* **Node Version:**
10.24.1

**Current behavior:**
Getting an error on `au build` which seems to relate to new release of enquirer.

* **What is the expected behavior?**
The build succeeds, currently using aurelia-cli to build in a pipeline. Steps are:
1. `npm install` 
2. `npm link aurelia-cli` 
3. then `au build`

Last step fails with:

```
node_modules/enquirer/lib/queue.js:4
  _queue = [];
         ^

SyntaxError: Unexpected token =
```

* **What is the motivation / use case for changing the behavior?**
To get our app building working again. 

Appears to work when I call: npm install enquirer@2.3.6 before the au build.

**Comment by AshWhitear** [comment]
Very appreciative and grateful for any help! Thanks! 🙏

**Comment by 3cp** [comment]
I will have a look. The worse case is to pin the version in our dependencies.

**Comment by 3cp** [comment]
The reason it failed you because you are using very very outdated nodejs v10.
It doesn't support class field definition.

```js
class SuchAs {
  aField = "init_val";
}
```

Nodejs v10 ended support in 2021. Please upgrade to latest LTS v18.

If you need to stay on nodejs v10 for a while. You can continue to use `npm install enquirer@2.3.6` (it touches your package.json so the version will stay in your project).
