### ISSUE TITLE
Distrobution Build

### ISSUE THREAD

**Issue by caperavensoftware** [aurelia/cli#124]
It would be really great if the build had a option for distribution where it will compile all the files you need for distribution into a single folder from where you can copy and past it. Right now I seem to have to do that manually and since I am still new to all of this I play guessing games as to what files I need to copy over and what not.

For the tool to take that pain out of the equation would be really great.

**Comment by rquast** [comment]
+1

**Comment by CharlesPockert** [comment]
I've got a gulp task setup for this.

There are a couple of options that I know of:

* Build an SFX (self executing bundle) which means you don't need to distribute the module loader
* Distribute system.js and es6-module-loader.js (if you are using runtime transpilation you also need your transpiler - I've not tried to get this working yet)

Note: you also need config.js to tell system what to load

My gulp task simply builds a bundled dist (under a subfolder) and then copies `system.js` and `es6-module-loader.js` from jspm_packages and my `config.js` into the root. 

Other stuff like the index/css (due to no css bundling yet) and images are copied manually using gulp tasks

Example here: http://charlespockert.github.io/aurelia-grid/ (check the number of requests on startup)

Would it be useful to show the gulp tasks?

**Comment by micros123** [comment]
+1
I'm trying to separate a bundled version from the development sources, also using the Aurelia-cli. But this doesn't take care of the main issue: The root of a project is full of all kinds of config and helper files (a bit of a mess to be honest) and it is not clear which ones you need in a ready-for-distribution deploy folder. 
Since config.js points to some packages in the jspm_packages folder, it seems like you need to have two folders with jspm packages.
Would be great if this got more streamlined.

**Comment by CharlesPockert** [comment]
@micros123 if you are bundling, the jspm_packages folder becomes part of your bundle and config.js is updated with the location of the js code itself (in the bundle file). In this case you don't need any jspm_packages folder. You only need:

* SystemJS - which is `system.js` and `es6-module-loader.js`
* `config.js` - tells system what to load
* your dist folder with bundles (js/css/html)
* `index.html` (obviously :smile:)
* any assets that didn't get bundled if any (images etc)

Also the CLI is deprecated in favour of https://github.com/aurelia/bundler, so you should use that instead (it supports CSS/HTML bundling)

**Comment by micros123** [comment]
Thanks, I'll try that and have a look at the bundler.
But the CLI is already deprecated? When searching for ways to bundle Aurelia apps, you easily end up on the extensive blogpost by Rob from only a few months ago: http://blog.durandal.io/2015/06/23/bundling-an-aurelia-application/
Hope we're not ending up with too many deprecated tutorials so soon :-)

**Comment by EisenbergEffect** [comment]
I can add a note to that blog post that points to the latest bundling library. That should help. I'll do that now.
