### ISSUE TITLE
Is anyone working with Webpack or thinking about that?

### ISSUE THREAD

**Issue by dschissler** [aurelia/cli#135]
I'm currently porting my Backbone application to a gulp + webpack build system with the ES2016 Babel transpiler (as much as possible since Backbone uses .Extend) and I'm considering rewriting the application with Aurelia in a year or two.  Does anyone have any thoughts on how Webpack would fit into the Aurelia build process?  I'm asking this because it seems that Aurelia is using jspm.

**Comment by EisenbergEffect** [comment]
Currently, Aurelia works with system.js, require.js and dojo loader. It does have a loader abstraction, so it is possible to implement new loading mechanisms. I'm not personally sure that web pack and similar tech is the way forward since it is a bit at odds with the ideas in ES6 modules and the ES6 module loader. So, I'm not sure we will directly support it. But if you want to implement a loader, we would be happy to add it to our registry for others.
