### ISSUE TITLE
Html bundling not working with globalizeResources

### ISSUE THREAD

**Issue by ochart2** [aurelia/cli#137]
I've added a pageable grid as a global resource into my app main.

aurelia.globalizeResources(['components/pager/pager','components/grid/grid']);

Once the app opens up, I get the following exception thrown:
http://localhost:3000/dist/components/grid/grid.html Failed to load resource: the server responded with a status of 404 (Not Found)

I also found a similar problem on stack overflow:
http://stackoverflow.com/questions/31364372/aurelia-two-templates-added-second-404s

**Comment by EisenbergEffect** [comment]
Can you provide me with some information for how to reproduce this using the navigation skeleton?

**Comment by cgoboncan-ebsi** [comment]
I was having the same issue as ochart2. I think the issue was because the template path resolved to an absolute path instead of an template id in the bundle. After upgrading from loader-default@0.9.0 to 0.9.1, I no longer have the issue. Before upgrading, i did try using the useView decorator, but that did not seem to have any effects.

**Comment by EisenbergEffect** [comment]
This may be related to the jspm beta changes. We had to add code to our loader to account with the change to urls for module ids. I think this sounds safe to close.

**Comment by ochart2** [comment]
Hi, Rob, so I think the last update i did was the one for the 2nd of July... is there a new update available to make this work?

**Comment by EisenbergEffect** [comment]
There is a new update going out today hopefully in Aurelia. There are also updates to the cli coming soon as well.
