### ISSUE TITLE
Aurelia CLI on ASP.NET Core

### ISSUE THREAD

**Issue by radenkozec** [aurelia/cli#233]
**I'm submitting a bug report**

* **Library Version:**
Latest

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
4.4.7

* **NPM Version:**
3.10.6

* **Language:**
 ESNext

**Current behavior:**
I have tried to set-up Aurelia on latest ASP.NET Core using CLI.
I am getting error attached in picture.

**Expected/desired behavior:**
Steps:
1) Platform -> ASP.NET Core
2) Transpiler -> Babel
3) CSS Processor -> None
4) Unit tests -> No
5) Create this project -> Yes
6) Install dependencies -> Yes

![aureliabug](https://cloud.githubusercontent.com/assets/3481625/16867571/d51fe8f0-4a72-11e6-9daf-c3da9aea7bfd.png)

**Comment by EisenbergEffect** [comment]
This looks like an issue with your npm install, which isn't likely a bug in the CLI itself. I can try to help you though. Can you copy the output from npm and paste it here. I suspect you aren't seeing all of the text due to the background color of your power shell. Also, you might try running this not through powershell. I know a lot of Windows developers use that, but it's not really a good tool for working with anything related to node or npm. It's better to use a bash shell. One final thought: make sure you have git installed.

Let me know if any of this helps or if you can provide more information.

**Comment by radenkozec** [comment]
As you suspected, powershell has hidden error messages, and yes I haven't got Git client installed.
Now everything works as expected.
