### ISSUE TITLE
[Feature Request] Support bundle SVG ICON files

### ISSUE THREAD

**Issue by XuJinNet** [aurelia/cli#290]
Many front projects use the SVG as ICON, i hope aurelia-cli can bundle it.

**Comment by AStoker** [comment]
It can. We're doing that right now. We're bringing SVG's in via the text plugin, since it's just XML like HTML is. You can look at the RequireJS Text plugin docs [here](https://github.com/requirejs/text#usage) to see how they're pulling in those text elements.   

From there you need to do a few things. You need to modify the `plugins` option in your `aurelia.json` file to add the `.svg` extension and set the `stub` to false (not entirely sure the purpose behind this, but it will fail if you don't).  
```
"plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css",
            ".svg"
          ],
          "stub": false
        }
      ]
```
And then for the most part recreate the `process-markup` task to process SVG files instead (you don't need to worry about the `changedInPlace` pipe in this task). If you start in the `build` file in the tasks folder, you can see how `processMarkup` is created and used. If you follow that pattern, you can add SVG support.  
Aurelia CLI is really just using gulp tasks for the most part, so you should be able to bundle those SVG's in there with a little elbow grease :) Let me know if you need more help.

**Comment by AStoker** [comment]
@XuJinNet, just checking back in, did you ever get this running?
I was just implementing this on a different project, and noticed some strangeness in the actual retrieval of the svg icon from the bundle.

**Comment by XuJinNet** [comment]
@AStoker I wrote a gulp task (process-svg.js), convert each SVG icon into a custom element.

**Comment by AStoker** [comment]
👍 Thanks. I think I actually started running into a RequireJS issue with how it loads up bundles.

**Comment by sbolel** [comment]
@XuJinNet same here. This is what we do pre-process-assets:

```js
function svgTemplates() {
  return gulp.src( 'assets/**/*.svg' )
    .pipe( $.rename( file => {
      file.extname = '.svg.html'
      return file
    }) )
    .pipe( $.change( contents => `<template>\n${contents}\n</template>` ) )
    .pipe( gulp.dest( `temp` ) )
}

And compose views using those templates to render the SVGs
