### ISSUE TITLE
Don't call css preprocessor if the no preprocessing is needed (raw css file)

### ISSUE THREAD

**Issue by bengypan** [aurelia/cli#298]
**I'm submitting a bug report**

* **Library Version:**
0.18.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.x

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all

* **Language:**
TypeScript X.X

**Current behavior:**
I selected sass as css pre-processor. in app.html, i had 
    `<require from="./styles.css"></require>`
but instead of having a styles.scss, i put styles.css file in the src folder.  so the page can't be loaded and complained:
but when i added , i started to see error on console: 
    `vendor-bundle.js:3740 Uncaught TypeError: h.load is not a function`
After i renamed styles.css to styles.scss, everything worked

**Expected/desired behavior:**

Ideally, if the styles.css is already a raw css file, the CLI should just load it as a css, without calling the scss preprocessor

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

**Comment by rc23** [comment]
You are a life saviour. I was having trouble with this for the past few days.

**Comment by jasonbiondo** [comment]
I also had the same issue!

**Comment by EisenbergEffect** [comment]
When you set up the CLI, you configured it for scss, so that's all it does. If you want to also handle standard CSS, you can go into the tasks folder and add your custom code.

I think we have this tracked as a potential enhancement to the default scss task in the future so I'm closing this as a duplicate. If anyone wants to PR that change, we'd love to have it.
