### ISSUE TITLE
au ru with asp.net core/typescript project cannot be served by browsersync correctly

### ISSUE THREAD

**Issue by ossentoo** [aurelia/cli#304]
**I'm submitting a bug report**
- **Library Version:**
  0.18.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.3.1
- **NPM Version:**
  3.10.6
- **Browser:**
  all 
- **Language:**
  TypeScript

**Current behavior:**
When running au run having configured the project for asp.net core/typescript, I get an error in multiple browsers (**Cannot Get**).  I think this is because the web server cannot serve the index.html file because it cannot find it.

I think the reason for this is that the base directory for the asp.net core project has been incorrectly configured.

the file **aurelia_project/run.ts** should have the line 26 changed from:

```
    baseDir: ['.'],
```

to

```
    baseDir: ['./wwwroot'],
```

because by default the configuration places the index.html for asp.net aurelia projects into the wwwroot folder.  When I manually made this change to my local project config, the Hello World page is able to be served.

**Expected/desired behavior:**

I expect the Hello World page to be served by the web server provided by au
- **What is the motivation / use case for changing the behavior?**
  This will enable the default project created by au for asp.net core to work correct with the command **au run**

**Comment by EisenbergEffect** [comment]
Would be great to see a PR to fix the CLI's setup in this case.

**Comment by nmocruz** [comment]
Even changing that, I still got an error loading scripts, is trying to load them from wwwroot/scripts, instead of scripts

404 --> http://localhost:9000/wwwroot/scripts/app-bundle.js

**Comment by mobilemancer** [comment]
This is my first pull request ever, so make sure the ceremonial things are in order :)

Added an additional file, so that there are separate run tasks for "au new --here" vs "au new" , so no conditionals introduced in any files.

**Comment by JeroenVinke** [comment]
@mobilemancer Thank you for creating the PR. A new issue that is the same as this one was opened recently: https://github.com/aurelia/cli/issues/531. The same fix came up (baseDir should be ./wwwroot for aps.net core projects) and a PR was created as well: https://github.com/aurelia/cli/pull/537

So now we have two different implementations of the same solution, which is great because we can compare them. What I wonder is whether or not supplying the proxy settings to browsersync is necessary for ASP.NET Core. Could you explain the reason for adding the proxy settings?

Since this issue is the same as #531, I will close this one so we can continue in https://github.com/aurelia/cli/issues/531 (you can still respond in this issue if you want though)

**Comment by mobilemancer** [comment]
@JeroenVinke The proxy settings I added was just to fix serving of the app via browsersync on port 9000. This didn't work for ASP.NET Core based projects before. It assumes that the cli setup is ok and serves properly from wwwroot. 

The basedir issue, that was not serving from wwwroot, was another problem.
