### ISSUE TITLE
Consider creating an "update-aurelia" command

### ISSUE THREAD

**Issue by jdanyow** [aurelia/cli#31]
After a release people need to manually `jspm install` each aurelia dependency, then `jspm clean` to tidy things up.  Should a cli command be added to automate this?

**Comment by PWKad** [comment]
I agree with this going through this issue now with updating a project and it's definitely a hassle.  I'm going to self-assign this one and PR when I get a good solution.

**Comment by PWKad** [comment]
@jdanyow What do you think about this - 

1. `jspm clean`
2. Iterate over the properties in package.json in the dependencies list
3. Call `jspm install {depName}` for each one

**Comment by PWKad** [comment]
As mentioned in the gitter I think we also need to add a `jspm unbundle` step in there

**Comment by jdanyow** [comment]
I think clean is the last step- otherwise sounds perfect

**Comment by PWKad** [comment]
Any thoughts on a `-nuclear` option here as well?  Deletes all local package folders and reinstalls everything.

**Comment by jdanyow** [comment]
that would be great- this option should probably clear the `map` property of the `config.js` file prior to running `jspm install`

**Comment by joelcoxokc** [comment]
@PWKad Keep in mind, you can use spawn-promise, to run jspm commands from the cli

**Comment by joelcoxokc** [comment]
This way the developer doesnt have to run jspm. Let me know if you need an example!

**Comment by zewa666** [comment]
Just keep in mind that this way you'd require the user to have jspm installed globally. Ok in our case it's no biggy since we have a hard dependency on that module. As an alternative JSPM also provides a nice API as npm module. Here is an example https://github.com/aurelia/cli/blob/master/lib/installer.js#L65-L68

**Comment by EisenbergEffect** [comment]
If at all possible, I think we should try to rely on the npm modules. That will make it easier for the editor tooling to use this and not have to worry about external installation of command line tools.

**Comment by PWKad** [comment]
@EisenbergEffect If we rely on NPM only that will prevent most users who are using JSPM from being able to use this no?  I wonder if we should just target the ~80% (made up math) for now and add flags and functionality later for npm only or w/e package managers when we have that requirement.

**Comment by EisenbergEffect** [comment]
I'm not sure I follow. Can't we use jspm's npm module that provides its capabilities as an api? or will that not cover the scenarios we need?

**Comment by PWKad** [comment]
Yes I think that's fine I missed @zewa666 's last point about JSPM through NPM.  My point is for our update command the way I've implemented ( @ahmedshuhel should be submitting the PR) it is to scan the config.js for dependencies and update those.  I thought you meant to use the aurelia packages that are available via npm instead of jspm which would not work (that I know of) in the skeleton because those packages are loaded directly through Github.

**Comment by EisenbergEffect** [comment]
Gotcha. This reminds me, do we need to publish the di and metadata libraries to npm in order for you all to use them?

**Comment by ahmedshuhel** [comment]
We have this command. We may need to polish it further but we may track the improvements in a separate issue.

**Comment by oS-So** [comment]
How would one be able to update the Aurelia packages using the Aurelia CLI? What is the recommended solution for this?
