### ISSUE TITLE
Option to not add a .js extension to dependency module

### ISSUE THREAD

**Issue by threeaccents** [aurelia/cli#313]
**I'm submitting a feature request**
- **Library Version:**
  0.18.0
- **Operating System:**
  OSX 10.x
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **Browser:**
  all 
- **Language:**
  TypeScript 1.9

**Current behavior:**
When adding a dependency to the `aurelia.json` file it automatically adds a .js extension. I'm running into the issue of trying to load the square javascript library which can only be used with their cdn. The cdn url does not have a `.js` extension `https://js.squareup.com/v2/paymentform`. 

**Expected/desired behavior:**
Have an extra option field where you can disable the adding of the .js extension or maybe a cleaner way to let the bundler know not the add the .js extension.

**What is the motivation / use case for changing the behavior?**
Trying to add payment processing to my app using square (https://squareup.com/). They don't allow their library to be used outside of their cdn so they don't have any `npm` or `bower` modules. I've tried adding a script tag in my `index.html` page but I can't use the library inside any of my classes since Aurelia does not know of the global variables from that file. I tried adding it to my dependencies like so:

```
{
   "name": "paymentform",
    "path": "https://js.squareup.com/v2/paymentform",
    "exports": "SqPaymentForm"
 },
```

But since Aurelia adds the .js extension it never finds the link

**Comment by AStoker** [comment]
I might take a stab at this after I get the version numbers working. My thoughts:
I’m thinking something like this, with having the options be an object so that we can add more options in the future
```
 {
            "name": “someModule",
            "path": "https://js.squareup.com/v2/paymentform",
            “options": {
                “noext”: true
            },
},
```
What do you think?

**Comment by rodzzlessa24** [comment]
I think its perfect. Maybe changing "noext": true -> "ext": false?

**Comment by EisenbergEffect** [comment]
@AStoker That works for me.

**Comment by AStoker** [comment]
That could work @rodzzlessa24

**Comment by EisenbergEffect** [comment]
@AStoker Still interested in this? I know you've got a few things brewing. Just let me know.

**Comment by AStoker** [comment]
@EisenbergEffect, it depends on the priority of this. I'm still trying to fix a bug with the CLI incorrectly bundling files, and I'm about to tap out on that one for a bit to work on getting TDD working with source code instead of bundled code.  
If somebody wants to make a PR, it might get done sooner. Otherwise, if it's still open when I finish up the other issues, I'll give it a quick shot.

**Comment by EisenbergEffect** [comment]
Sounds good.

**Comment by Alexander-Taran** [comment]
Looks stale since 2016
was brought up on gitter

**Comment by EisenbergEffect** [comment]
I'd love to get a community contribution for this.

**Comment by Alexander-Taran** [comment]
@3cp interesting one (-:

**Comment by 3cp** [comment]
I don't think this is in our control, it's the default behavior of requirejs when loading module from remote.

**Comment by 3cp** [comment]
Current cli doesn't support deps defined with path starting with `http(s)://`.
It could be some dropped feature since v0.18.0.

I am pretty sure the previous feature uses requirejs config paths, where requirejs adds "missing" `.js`. That's not in our control.
```js
requirejs.config({ 
  paths: {
    "paymentform": "https://js.squareup.com/v2/paymentform"
  }
  ...
```

However, that js lib is in legacy format, only suppling a global var `SqPaymentForm`, it should be loaded by prepend instead.

Unfortunately cli's prepend doesn't support remote link.

The successor of cli bundler, [dumber bundler](https://dumber.js.org/options/prepend-and-append) does support remote url in prepend and append. I tested it, confirmed `"https://js.squareup.com/v2/paymentform"` works without the annoying `.js`.
