### ISSUE TITLE
Feature Request: change cli folder to .au

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/cli#327]
**Current behavior:**
aurelia cli creates and operates via project folder `aurelia_project`

**Desired behavior:**

create and operate via project folder `.au`
fallback to `aurelia_project` if `.au` doesn't exist

**why** 
less imposing folder name on the project tree. 
would be topmost folder name in the project tree. 
mimics other tooling's convention (e.g. `.vscode`)

**Comment by AStoker** [comment]
Usually files that start with a dot (`.`) indicate some kind of hidden folder, or a folder that you don't interact with. On a Mac system, files that start with a `.` _are_ treated as hidden folders.  
Since the `aurelia_project` folder is one that users do interact with, I'm not sure hiding it would be desirable. Perhaps just naming `au` instead of `.au` would be sufficient?

**Comment by EisenbergEffect** [comment]
Yeah, we don't want to use a "dot" folder name. I'm closing this for now.

**Comment by MeirionHughes** [comment]
okay how about this then: 
* leave the default as aurelia_project
* [optional] add a property in package.json: `au`: `aurelia_project`
* cli reads folder as `require('package.json').au || "aurelia_project"`

this allows people like me to move the folder without changing it for the majority of people. (I'm happy to PR this change btw, if you will allow it).

**Comment by grofit** [comment]
I kinda like this approach but I think currently the `aurelia_project` folder has too much responsibility, so currently it contains generator and aurelia config stuff as well as environmental vars and build tasks.

Almost every js project I have worked on before has a build folder and pushes tooling specific vars/config elsewhere, so it may be a compromise to have the `.au` folder for the `aurelia.json` and `generators` folder and just put the environments and tasks folders into a `build` folder.

**Comment by EisenbergEffect** [comment]
@grofit That sounds reasonable. If you can PR that, I don't see why we can't put that in.

**Comment by grofit** [comment]
The only thing I have noticed is that the aurelia.json is also used by the build (not gulp but the `au` CLI) for bundling etc so that kinda borders on doing 2 things, so I think this may need more thought as like mentioned earlier generally `.somefolder` implies its just metadata a dev never needs to play with (which should be true for the generators) but a developer may need to change the aurelia.json file.
