### ISSUE TITLE
'au new --here' gives different output from 'au new'

### ISSUE THREAD

**Issue by lunicleonid** [aurelia/cli#334]
**I'm submitting a bug report**

* **Version:**
> au -v
0.18.0

**Please tell us about your environment:**
* **Operating System:**
Windows  10

* **Node Version:**
v4.4.7

* **NPM Version:**
3.9.5

**Current behavior:**
> au new --here
...
What platform are you targeting?

1. Web (Default)
   The default web platform setup.
2. ASP.NET Core
   A powerful, patterns-based way to build dynamic websites with .NET.

[Web]>

----------------
au new zz
...
Would you like to use the default setup or customize your choices?

1. Default ESNext (Default)
   A basic web-oriented setup with Babel for modern JavaScript development.
2. Default TypeScript
   A basic web-oriented setup with TypeScript for modern JavaScript development.
3. Custom
   Select transpilers, CSS pre-processors and more.

[Default ESNext]>

**Expected/desired behavior:**
I would expect that both would give me the same output :)

**Comment by EisenbergEffect** [comment]
They serve different purposes. If you specify `--here` it will first ask you if you have setup a particular backend technology "here" before it asks you the other questions. That is important because, depending on the platform, the folder structure may need to be set up differently. If you want the same options as not using `--here` then you should select the default web platform.

**Comment by lunicleonid** [comment]
Thank you.
