### ISSUE TITLE
upgrade path for aurelia-cli projects is unclear

### ISSUE THREAD

**Issue by guidorice** [aurelia/cli#336]
**I'm submitting a feature request**
- **Library Version:**
  0.20.0

**Current behavior:**

Consider this use case:
- create a project with aurelia-cli.
- later, various aurelia packages are released with bug fixes or features.
- later, aurelia-cli itself is updated with bug fixes or features.

Unclear how to upgrade, because `au new` is just like a snapshot at that point in time.

**Expected/desired behavior:**
1. Please add an option to aurelia-cli to update an au project to the latest version. For example, there is a javascript code in aurelia_project/tasks/ that I assume will get out of date. Also what if new stuff needs to be added to aurelia.json, or removed from aurelia.json?
2. Please add an option to aurelia-cli to update aurelia and all it's dependencies to latest versions from npm.
- **What is the motivation / use case for changing the behavior?**

It is very time consuming trying to figure out all the dependencies in package.json as well as how to upgrade aurelia-cli. 

If you don't think this belongs as an option for aurelia-cli, then maybe it could be added to the documentation hub somewhere.

**Comment by EisenbergEffect** [comment]
It's all npm under the hood. To update, just use npm. We can add a note on this to the docs.

**Comment by guidorice** [comment]
ok thanks Rob

**Comment by michielcornille** [comment]
When cloning a github repo, and installing aurelia-cli on a newer version than the one used in the repo, au run does not work.
It would be nice if the error message would say "aurelia-cli  version incompatible" instead of 'invalid command run'

**Comment by Ganbin** [comment]
I still have this problem on my Mac OS X El Capitan. I have updated my aurelia-cli from 0.18 to 0.21. But now I'm unable to run `au run` it say `Invalid Command: run`.

I have remove the cache from NPM like say in the doc but it doesn't solve the issue. So Now I think I have to recreate a new project using au new and then migrate all my files, and changes, Which take time and can lead to some error. I know this is still in alpha phase so I think the upgrade of the aurelia-cli is a main issue specialy to help to improve it we should be able to upgrade more easly, I think some instruction on the way we can do it could be much appreciable.

**Comment by MeirionHughes** [comment]
@Ganbin I've had that too; bar uninstalling the cli entirely, cleaning the cache and updating to npm 3.10... I guess you could do a blanket string conversion to replace `\\` with `/`

**Comment by Ganbin** [comment]
I have made the migration by moving all my files in a `TEMP` folder and then do a `au new --here` in my project folder.

Here is the steps I have follow : 

1. Move the content of `./TEMP/src/` to `./src/`.
2. Move the content of `./TEMP/styles/` to `./styles/`.
3. Move the config files (like `.editorconfig`, `.eslintrc.json`)
4. Check the content of the `package.json`and install the dependencies. You can install them by adding them directly in the `package.json` and then run a `npm install` or install them with `npm install <package_name> --save`.
5. Add the dependencies in the `/aurelia_project/aurelia.json`. Check the `/TEMP/aurelia_project/aurelia.json` to see how you have add the dependencies in this file.
6. Be sure to keep all the modification you have done in the previous version of your project in the `aurelia_project` folder if for example you have add some proxy middleware config in the `task` files.

Last advise. Check if some dependencies need some upgrade since the last installation and if you need to adapt the `aurelia.json` config file, which was the case for me when using the `aurelia-materialize-bridge`.

Hope this will help. The migration is not so complicated in fact if we keep all our dependencies and modification track. I recommand you to write in a note somewhere all your modification outside the `src` folder.

**Comment by JeroenVinke** [comment]
Lets continue in https://github.com/aurelia/cli/issues/231 which is also about improving the update path of the CLI
