### ISSUE TITLE
Cannot find any tasks

### ISSUE THREAD

**Issue by MeirionHughes** [aurelia/cli#354]
`au -v`: 0.20.1
OS: Windows 10
`node -v`: 6.7.0
`npm -v`:  3.7.5
language: typescript

**Current behavior:**
`au X` returns error: `"Invalid Command: X"`, where X is a defined task i.e. `./aurelia_project/tasks/X.json`

**Expected/desired behavior:**
run the gulp task

0.20.0 is unaffected. 
tested with cli versions matching (local and global).

**Comment by MeirionHughes** [comment]
clearing npm-cache and reinstalling seem to have fixed it.

**Comment by AStoker** [comment]
Not sure if this is what you had, but I experienced something like this a while ago. I think it ended up being due to how I installed the `au` command. Instead of running `npm install aurelia-cli -g`, I ran `npm install au -g`. Not sure what the heck that did, but it did put the `au` command on my window, but when I tried to run command, I'd get what you had. Anyway, just a thought.
