### ISSUE TITLE
Plugins using a config-builder pattern don't load this builder from the bundle

### ISSUE THREAD

**Issue by Thanood** [aurelia/cli#384]
**I'm submitting a bug report**
- **Library Version:**
  0.21.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.2.2
  
  
- **NPM Version:**
  3.9.5
  
  
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**

I tried adding a plugin to my app. This plugin uses an index file with a "config-builder" (not sure how to call it) to a _separate_ bundle. I've used [aurelia-v-grid](https://github.com/aurelia-ui-toolkits/aurelia-v-grid) and [aurelia-materialize-bridge](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge).

The bundle config for `aurelia-v-grid` looks like this:

``` json
      {
        "name": "v-grid-bundle.js",
        "dependencies": [
          {
            "name": "aurelia-v-grid",
            "path": "../node_modules/aurelia-v-grid/dist/amd",
            "main": "index",
            "resources": [
              "vGrid/v-grid-element-footer-pager.js",
              "vGrid/v-grid-element-row-repeat.js",
              "vGrid/v-grid-element-col-config.js",
              "vGrid/v-grid.js",
              "vGrid/v-grid-attributes-sort.js",
              "vGrid/v-grid-attributes-filter.js",
              "vGrid/v-grid-attributes-selection.js",
              "vGrid/v-grid-attributes-image.js",
              "vGrid/v-grid-attributes-key-move.js",
              "vGrid/v-grid-attributes-contextmenu.js",
              "vGrid/v-grid-attributes-observe-field.js",
              "vGrid/v-grid-attributes-dragDropCol.js",
              "vGrid/v-grid-attributes-resize-col.js",
              "vGrid/v-grid-element-footer-pager.html",
              "vGrid/v-grid.html",
              "vGrid/styles/v-grid.css",
              "vGrid/styles/v-grid-draggable.css",
              "vGrid/styles/v-grid-contextmenu.css",
              "vGrid/styles/v-grid-loader.css",
              "vGrid/styles/v-grid-pager.css",
              "vGrid/styles/v-grid-sorticon.css",
              "vGrid/styles/v-grid-optional.css"
              ]
          }
        ]
      }
```

Please note the main entry point is `index`.

When I use this plugin in an aurelia-cli app using this line in `main.js`:

``` javascript
aurelia.use.plugin('aurelia-v-grid');
```

The file `index.js` from said plugin is loaded from `node_modules` instead of its bundle.

This behavior can be fixed by adding `index.js` to the resources array. In my opinion, this shoudn't be necessary and therefore I found it confusing because the file `index.js` is the main entry point already and as such, should already be bundled.

**Expected/desired behavior:**

- **What is the expected behavior?**

When loading a plugin with `aurelia.use.plugin`, the index file should not be loaded from `node_modules` but from the bundle. It should (IMO) not be necessary to add the bundle's main entry point to the resources array.

**Steps to reproduce**:
- `npm install git://github.com/aurelia-ui-toolkits/aurelia-v-grid.git --save`
- add the bundle config shown above to `aurelia.json`
- call this in `main.js`: aurelia.use.plugin('aurelia-v-grid');
- watch the network tab in chrome, look for `index.js` - you should see that it is loaded from `node_modules`

**Steps to make it work**:
- add `index.js` to the `resources` array of the bundle configuration
- watch the network tab in chrome, look for `index.js` - it should not be there

**Comment by EisenbergEffect** [comment]
That's very odd.

**Comment by JeroenVinke** [comment]
I looked at this issue today and was able to reproduce it:

![image](https://cloud.githubusercontent.com/assets/2189477/23339395/804b85ee-fc21-11e6-8a03-1de820f8a67e.png)

In the RequireJS config I noticed the following:

![image](https://cloud.githubusercontent.com/assets/2189477/23339358/e453e56e-fc20-11e6-9b7f-fd611c4b26ee.png)

And I believe this is due to [this guard](https://github.com/sbolel/cli/blob/master/lib/build/bundled-source.js#L129-L131). The result is that the `aurelia-v-grid/index` module is put into the bundle configuration under the name `aurelia-v-grid` instead of `aurelia-v-grid/index`, so when RequireJS is asked to fetch `aurelia-v-grid/index` (because of `.plugin('aurelia-v-grid')`) it thinks that it doesn't have this file in the bundle and tries to fetch the index.js file. 

I wonder if it's necessary to have both `aurelia-v-grid` and `aurelia-v-grid/index` in the bundle configuration. @AStoker what do you think is the best way to resolve this?

**Comment by Alexander-Taran** [comment]
@3cp is this relevant to current bundling solution?

**Comment by 3cp** [comment]
Current aurelia-cli bundler does not need any of those explicit config. Pls reopen if there is something wrong after removing config for those plugins.
