### ISSUE TITLE
Writing bundles to index should be relative to index

### ISSUE THREAD

**Issue by ShaunVanDyk** [aurelia/cli#398]
**I'm submitting a bug report**
- **Library Version:**
  Aurelia CLI 0.21.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.5.0
  
  
- **NPM Version:**
  3.10.8
  
  
- **Browser:**
  all
- **Language:**
  all 

**Current behavior:**
If I have this as my configuration in aurelia.json:
"build": {
    "targets": [
      {
        ....
        "output": "dist",
        "index": "dist/index.html"
      }

I'm saying I want my files to be output to the folder dist, and my index is located in dist already, so dist/index.html. However as part of the bundling process it tries to write in my index file that the scripts are at dist/vendor-bundle.js even though relative to index it is just vendor-bundle.js. Even if I were to change my bundle names to be scripts/vendor-bundle.js, it will put them in the dist/scripts/ folder, and then try to write in my index.html file that it's located at dist/scripts/x even though relatively it is /scripts

**Expected/desired behavior:**

It should either write the scripts relative to where index.html is located, or have a setting so you can specify it yourself. At the moment you only have "output" to tell it where to copy the scripts and "index" to tell it where your index file is located. Looking at https://github.com/aurelia/cli/blob/master/lib/build/bundle.js line 153, you can see that if you have the index file property defined (if you don't I would suggest logging a warning so the user knows they haven't specified it as at the moment you don't realise the process couldn't write to it if you didn't specify it, which may be desired), then it does a simple path.join of the output dir with the bundle file name, which will only work if your index is in your root folder.

**What is the motivation / use case for changing the behavior?**
1) Have one folder where your build is contained so you can just take this folder as a root and deploy it to where you need to.
_To deploy the default project that is built using au new, you would need to copy index.html, pick the scripts folder as well as styles / assets etc., as well as the favicon.ico. You don't want to just copy everything in the folder because it contains all other configs and build files etc. that aren't relevant for prod. If you want to automatically deploy the application using a build server, this becomes a bit messier than just saying *copy all contents from dist and deploy to //server/website._

2) All source code in the src folder instead of the root directory.
_I don't want index.html in my root folder, again with all the other build files / config / node modules etc. I want it in my src folder, because it's part of the code I've written._

3) Not having the build process alter my source file index.html
_As discussed above, I have a separate copy of index.html which acts as my template that I can alter. I've created a task myself to copy this into the dist folder and let the build process alter that version of it. I just don't feel comfortable having the build process alter my one version of index.html, if the build process fails, does something wrong, whatever, I want to be able to just blat away the dist folder and know everything the build has done is gone, easy clean! Also you want to check-in the index.html file because it is your template, but every time each dev builds it locally, it may alter the file (depending what you have going on), which means you would get conflicts all the time._

For now I'm creating all my files in my root directory so it is flat there, then I've created additional tasks to move them into the dist folder.

**Comment by AStoker** [comment]
I'm trying to follow everything you have going on, so bear with me :)
It looks like you're trying to put your `index.html` file in the same directory as where you output your transpiled code. That's probably where the problem lies for you, and you might benefit from separating out your transpiled code (`dist`) from your index file which isn't transpiled/bundled. Is there a specific reason why you need to have it all inside `dist`?  
If you're wanting to have a single folder that contains everything that needs to be deployed, there's nothing stopping you from doing that. Aurelia just uses Gulp under the hood, and you can create a gulp task that takes all those files you're talking about and copy them into a `deploy` folder. The ASP.NET skeleton that Aurelia-CLI makes actually puts everything inside a `wwwroot` folder and behaves exactly like you are describing.  
If you don't want your `index.html` in the root folder, then move it and tell the `aurelia_project.json` file where everything is. It's not locking you down.  
The build process alters the `index.html` if you are using build revisions, because when you create a new build number, the `index.html` needs to know what the file is that gets loaded up. Again, since it's just using gulp, you could do some file reading and copying to ensure that any failure doesn't mess up the `index.html`. But if you have a failure, you're going to have bigger problems than the index file being hosed, because your application won't work anyway.  
I think your problems are coming mostly from how you want your project to be structured, and then getting that structure to be represented in the aurelia json file.

**Comment by ShaunVanDyk** [comment]
Hi AStoker,

Thanks for the response. I already ended up getting the build to do what I want by creating some custom Gulp tasks after spending a bit of time trying to work out what was going on :)

I was testing out the revision stuff which is why I needed to ensure that the build could successfully alter my index.html file. However the issue is I don't think this alteration will work if you ever move index.html outside of the root. Altering the aurelia.json file will successfully let the build process find it and alter it, however the path that would be written would be wrong. So even if I was to do something like this:
- root
-- dist
-- index.html
-- scripts
--- vendor-bundle.js
And told Aurelia my output folder is "dist/scripts" and my index file is in "dist/index.html" and I serve up my pages from here or copy the folder as is, then the index.html file will be altered to point to "/dist/scripts/vendor-bundle.js", but dist doesn't exist in the deployed folder.

If I use the default folder structure it does work fine, I just feel like the default structure doesn't nicely separate out my files into each of their concerns :(
