### ISSUE TITLE
Trace dependencies is never set to false for resources

### ISSUE THREAD

**Issue by rkrdovrgs** [aurelia/cli#400]
**I'm submitting a bug report**
- **Library Version:**
  0.21.0

**Please tell us about your environment:**
- **Operating System:**
  Windows 7
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.9.6
- **Browser:**
  all
- **Language:**
  TypeScript

**Current behavior:**
- Not possible to add a bundle dependency that has resources, and you want to disable `traceDependencies` by setting the pattern using `[]` [see here - line 12](https://github.com/aurelia/cli/blob/master/lib/build/source-inclusion.js#L12)
- For the following dependency:

``` json
{
   "name": "my-dependency",
   "path": "../node_modules/my-dependency/amd",
   "main": "index",
   "resources": [
      "[**/*.js]"
   ]
}
```
- Pattern is supposed to disable trace dependencies, but when it is evaluated, pattern value becomes  `"../node_modules/my-dependency/amd/[**/*.js]"`. Two things ocurred:
-  `pattern[0]` is not equal to `'['` meaning `this.traceDependencies` is set to `true`.
- The pattern will not return any matches.
- Also typo on [line 10](https://github.com/aurelia/cli/blob/master/lib/build/source-inclusion.js#L10)

**Expected/desired behavior:**
- **What is the expected behavior?**
  The pattern disables `traceDependencies` and the pattern return matches.
- **What is the motivation / use case for changing the behavior?**
  Allow disabling `traceDependencies` for dependency resource patterns.

**Comment by AStoker** [comment]
Just to clarify, you're wanting to be able to trace dependencies by using the bracket (`[]`) syntax for resources, right?
The bracket syntax is specific to Aurelia, not a minimatch/glob feature. So I believe it's only good for defining source locations. Dependencies and resources I think have to be more specific. You'd probably want to be real careful trying to trace resources of dependencies, as you might add a large amount of time tracing things like jQuery or other paths. That's why you have a `deps` option for resources, so you can define what dependencies are needed for this dependency.   
Could you give a use case for wanting this kind of feature?

**Comment by rkrdovrgs** [comment]
@AStoker no, I am talking about the opposite. I want to be able to disable tracing by using the brackets. This is not an enhancement, this is a bug. As you suggested, I actually was talking about a dependency:
```
{
   "name": "bundle-name.js"
   "dependencies": [
      {
         "name": "my-dependency",
         "path": "../node_modules/my-dependency/amd",
         "main": "index",
         "resources": [
            "[**/*.js]"
         ]
      }
   ]
}
```

I want to be able to disable traceDependencies by using the square brackets, but there is a bug in the code that prevents that. Please see https://github.com/aurelia/cli/blob/master/lib/build/source-inclusion.js#L12.
- Pattern is supposed to disable trace dependencies, but when it is evaluated, pattern value becomes `"../node_modules/my-dependency/amd/[**/*.js]"`:
`pattern[0]` is not equal to `'['` meaning `this.traceDependencies` is set to true.

**Comment by 3cp** [comment]
This is now irrelevant to latest cli-bundler which auto-traces everything.
