### ISSUE TITLE
can't add dependency of package containing relative imports

### ISSUE THREAD

**Issue by k2s** [aurelia/cli#428]
I can't get following package loaded with `dependencies` section in `aurelia.json`.

I have installed:
```npm install --save redux-immutable```

After some fiddling I added to dependencies:

```
          {
            "name": "redux-immutable/utilities",
            "path": "../node_modules/redux-immutable/dist/utilities",
            "main": "index"
          },
          {
            "name": "redux-immutable",
            "path": "../node_modules/redux-immutable/dist",
            "main": "index"
          }
```

unfortunately `au build` ends with error: `/home/me/prjName/redux-immutable/utilities/getStateName.js''` Correct would be ` /home/me/prjName/node_modules/redux-immutable/dist/utilities/getStateName.js`.

I can't find way to overcome this message. I expect that already the need to add `redux-immutable/utilities` into dependencies manually comes from the same root problem: Aurelia build is not able to handle relative imports like `var _utilities = require('./utilities');` 

I found similar problem here: http://stackoverflow.com/questions/40187364/using-aurelia-cli-with-npm-packages-containing-relative-requirejs-imports-speci/40204907

**Comment by AStoker** [comment]
Why do you have two dependencies listed here? They're both from the same package, I imagine you'd only need one.

**Comment by AStoker** [comment]
Part of their problem is that they have bad requests for files (they don't follow how RequireJS loads files). Node's `require` syntax is a bit different from RequireJS (mostly in how it asks for files). Node's version is a bit more flexible, so you can make a request like `require('./getStateName.js')`, but RequireJS requires files that have been requested via a relative path to be defined without the `.js`, [definition](http://requirejs.org/docs/api.html#jsfiles)  
> RequireJS also assumes by default that all dependencies are scripts, so it does not expect to see a trailing ".js" suffix on module IDs. RequireJS will automatically add it when translating the module ID to a path  
So the library itself needs to be changed so that requests for files don't have the `.js` extension. Node will still work fine with this, and it will be more friendly to browser based module loaders.

**Comment by k2s** [comment]
two dependencies are there only because I was already trying to solve it that way

the package seams to be published like this https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/

Is there plan to support loading such packages with Aurelia CLI, I am using **the same package with webpack skeleton and that works without issues**.

**Comment by AStoker** [comment]
The problem isn't with the CLI, _but rather with how the RequireJS module loader asks for files_. That article seems right (only looked over it briefly), but it doesn't mention how to use require tags (that I saw). The reason it probably works with other setups are because _they use different module loaders_. But your library is being compiled to AMD by the author, and if you're following AMD, you're most likely using RequireJS, in which case it's bad code.   
So it comes back to the author, the way they're asking for files is "sometimes" right, and it's worked for them so far. But it is _not_ AMD compatible. A simple PR would fix the issue, because you need to do little more than remove the `.js` extension from the requests.

**Comment by k2s** [comment]
@AStoker thank you very much, seams I was really able to build working version after fixing few issues in their code. 

will commit PR to redux-immutable after I test my changes really work

**Comment by AStoker** [comment]
Glad to help. We had this issue with another repo recently, and fixed it by submitting PR's to their project. So this isn't the first time :) There's some mixed practices out there.
