### ISSUE TITLE
Add jshint dev task in aurelia-cli generated project?

### ISSUE THREAD

**Issue by oivinds** [aurelia/cli#429]
How do I add i.e jshint to dev tasks for aurelia to run?

**Comment by AStoker** [comment]
Thanks for using Aurelia!  
We're trying to keep questions over at Stack Overflow and our Gitter channel, and keep issues over here. This really helps us properly manage issues and keep things clean, and also helps users ask questions in places they're more likely to get help.  
If you could do me a favor and ask that question over in SO, and then post the link here so that I can try and help you there, I'd appreciate it. In the mean time, I'm going to close this issue since it's a question.
