### ISSUE TITLE
TypeScript : baseUrl in tsconfig.json

### ISSUE THREAD

**Issue by Creadigme** [aurelia/cli#458]
**I'm submitting a bug report**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

* **Browser:**
all

* **Language:**
TypeScript 2.1

**Current behavior:**

If I use "baseUrl" in "tsconfig.json", aurelia-cli won't transpiler any source.

"baseUrl" is mandatory for use absolute path in imports.

**Expected/desired behavior:**

1) open tsconfig.json
2) add "baseUrl": "./src" in "compilerOptions"
3) au build

* **What is the expected behavior?**

Transpilation & bundle.

* **What is the motivation / use case for changing the behavior?**

My project is a plugin, thus I need absolute path.

Workaround is to put an absolute path in baseUrl, however it's not a good solution.

**Comment by EisenbergEffect** [comment]
What do you mean by "plugin"? Is this designed to be an Aurelia framework plugin? If so, the CLI isn't the best way to build that. Instead, consider using our skeleton-plugin repo as a starter kit.

**Comment by Creadigme** [comment]
All my "plugins" can be launch alone, thus there not just "aurelia plugins" but real projects.

By the way, this "baseUrl" bug exist, my internal use has no matter. You can reproduce with : 
- au new, typescript
- add "baseUrl": "./src" in "compilerOptions"
- au build


Why we use aurelia-cli for our "plugins/applications" ?
- Bundle : I want only one file by plugin/application.
- One CLI for all our projects.
- Custom task for generate *.d.ts and bundle in one index.d.ts.

We use aurelia-cli for all our projects since september 2016 with no issue.

I have seen the baseUrl bug when we have switched to TypeScript.

**Comment by mdemmers** [comment]
- Operating System:
Windows 10

- Node Version:
6.9.1

- NPM Version:
3.10.8

- Browser:
all

- Language:
TypeScript 2.0.1

Experiencing the same issue. When using the baseUrl option in the compileroptions of tsconfig, sources don't get transpiled and bundled. It seems that the typescript transpiler from aurelia_project/tasks/transpile.ts can't find the sources or aurelia is doing some mapping of some kind internally. In aurelia.json i have the following configuration (provided by au new command) 

"transpiler": {
    "id": "typescript",
    "displayName": "TypeScript",
    "fileExtension": ".ts",
    "dtsSource": [
      "./typings/**/*.d.ts",
      "./custom_typings/**/*.d.ts"
    ],
    "source": "src/**/*.ts"
  }

I tried to change the source path with different options but with no avail. It is unclear what effect baseurl has on the source location of ts files or with aurelia itself.

The typescript compiler withing visual studio 2015 allows for imports like import {barentity} from 'entities/foo/bar' instead of doing import {barentity} from '../../../../entities/foo/bar' when baseUrl is set. Using this option increases cleaner and consistent usage of imports.

**Comment by mdemmers** [comment]
Issue resolved. There were multiple issues. Typescript installed a global compiler in the program files folder and added this to the path variable, with compiler version 2.0. When running tsc from cmdline (from any localtion) in my aurelia project folder there were multiple errors. I removed the windows path variable so when running tsc it would resolve to the locally installed typescript compiler with version 2.2.1.

At this stage there were multiple typescript errors but different ones before running with the 2.2.1 compiler. After some googling it looked like that the errors came from incompatible version mismatch between gulp-typescript (used by transpile.ts from aurelia_project) and the locally installed typescript compiler. I updated the gulp-typescript library to version 3.1.6 and the errors went away but new errors were raised. The "typings" and "custom_typings" folder are included by default in aurelia.json when using au new. This raised a lot of errors because tsc tries to compile all the .ts files in this folder. Fixed this issue changing following line in transpile.ts:

return eventStream.merge(dts, src)

to

return eventStream.merge(src) 

I don't know if this is the best solution but for now this works.
