### ISSUE TITLE
aurelia-cli: 'au run' after a fresh install returns error

### ISSUE THREAD

**Issue by goyb** [aurelia/cli#488]
I just donwloaded the aurelia-cli, created a new project (typescript) and installed all the dependencies. However, trying to run the app through the `au run` returns in an error:

**Error: File not found with singular glob: C:\AURELIA\todo\aurelia_project\environments\development.ts**

It's looking for a development.ts in the aurelia_project/environments folder while it created only a dev.ts file. 

**npm -v : 3.10.8
node -v: 7.0.0**

Changing the **dev.ts** to **development.ts** fixes this problem.

**Comment by goyb** [comment]
****

**Comment by AStoker** [comment]
@goyb, so this comes down to Node actually (luckily spent a few hours solving this with someone else before). The CLI is trying to determine your build environment. You can provide one manually be adding the `--env prod|dev|stage` flag. By default, it chooses `dev`. _HOWEVER_, it will look at your node environment as well, and use that one if it can. Your node environment is probably set to `development`, and therefore it's trying to find a file matching that build environment.  
You could either change your environment to `dev`.  

Take a look [here](http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows) for how to change your environment in windows.

**Comment by AStoker** [comment]
For reference as to where this is happening in the CLI, look [here on line 9](https://github.com/aurelia/cli/blob/3c5ea5f935e523d1cec5ead884391d6b008deee5/lib/cli-options.js#L9)

**Comment by goyb** [comment]
You are correct about my **NODE_ENV** variable, it was indeed set to **'development'**. 

It didn't take me long to figure out, but I reported this because it was my first experience with the framework :). It would be shame to put people off from using it.

**Comment by AStoker** [comment]
Perhaps it would be a good idea notify on building if the environment being run is different than one's we're expecting, or different than any we have defined in our `environments` folder? @EisenbergEffect, you think that would add value?

**Comment by EisenbergEffect** [comment]
Yes. I think that would be a good idea. This has happened several times to
people thing of the CLI.

**Comment by AStoker** [comment]
👍 I'll take a crack at it.

**Comment by AStoker** [comment]
Looks like we have two options.  
1. We add a log function to the default `configureEnvironment` function. Any _new_ aurelia project will have a simple check to see if the file exists, and if it doesn't, it'll log out a possible reason for it. Benefit to this is that it's dynamic in that if a user decides to name an environment something completely different, they can account for it. Con is that it won't solve any existing CLI user's errors.  
2. We add a check in the `getEnvironment` function to determine if we're using the built in `NODE_ENV`, and if so, that the `NODE_ENV` is either `dev`, `stage`, or `prod`. If it's not one of those, we simply log out a quick message saying 
> The selected Node Environment is not a preconfigured option (`dev`, `stage`, and `prod`)   

That would let anybody know that if it's not one of those, that a problem _may_ occur, but we're not saying that what they're doing is wrong. Benefit of this is that all CLI users would get this check. Con is that if a user _does_ have a specific node environment they want to be running in (other than a preconfigured option), they would be getting this message as noise. 

I'm leaning towards option 2, as it would catch the most cases with the tradeoff of some (I imagine a smaller minority) users getting extra noise. Unfortunately, since the environment location isn't defined anywhere other than the actual transpile operation, we're not able to reliably check to see if the file for the environment exists before we actually ask for the file.  
What are you thoughts @EisenbergEffect ?

**Comment by AStoker** [comment]
Errors would look like the following:
```
Andrews-iMac:astoker.github.io astoker$ au build
Starting 'readProjectConfiguration'...
The selected Node Environment (foo) is not a preconfigured option ('dev', 'stage', and 'prod')
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processSVG'...
Starting 'processCSS'...
Starting 'configureEnvironment'...
The selected Node Environment (foo) is not a preconfigured option ('dev', 'stage', and 'prod')
{ uid: 7,
  name: 'configureEnvironment',
  branch: false,
  error: 
   { Error: File not found with singular glob: /Users/astoker/Documents/Github/AStoker/astoker.github.io/aurelia_project/environments/foo.js
...
```
So every time that `getEnvironment` is called, it would notify the user of something strange. I imagine this would be enough, as long as somebody looked at the top of the error, they would see that notification, as well as the "File not found..." error, and dots should be connected.
