### ISSUE TITLE
CLI to add resource files on "install" and "import"

### ISSUE THREAD

**Issue by didzis** [aurelia/cli#538]
**I'm submitting a feature request**
The new CLI features "import" and "install" could add other files in dist folder as resources, for example, after installing bootstrap it would be nice to have ```resources:[css/bootstrap.css]``` added in aurelia.json so it could be imported/requested in the project.

**Comment by JeroenVinke** [comment]
Thanks for creating this issue, and it would be nice to have the bootstrap CSS resource. 

The importer currently supports looking for resources. If it finds CSS files it will ask you whether or not you would like to use them. If so, it will add those CSS files to the resources property and explain how to import them using `<require>` tags. But because we have defined a configuration for bootstrap in the registry ([here](https://github.com/aurelia/cli/blob/master/lib/importer/registry/bootstrap/0.0.0.json)) it doesn't do this and simply uses the configuration from the registry, which does not define resources. So we have to add it to [this file](https://github.com/aurelia/cli/blob/master/lib/importer/registry/bootstrap/0.0.0.json)

Would you like to create a PR?
