### ISSUE TITLE
Karma cannot find app and verndor bundles when build revisions are enabled

### ISSUE THREAD

**Issue by jimmyvdberg** [aurelia/cli#554]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

* **Operating System:**
Windows 10

* **Language:**
TypeScript

**Current behavior:**
When creating a new Aurelia project using the CLI `(au new)` with unit testing and build revisions enabled. I get a warning message that karma cannot find the `vendor-bundle.js` and `app-bundle.js`.

> 14 03 2017 08:54:27.260:WARN [watcher]: Pattern "C:/Temp/AureliaTest/scripts/vendor-bundle.js" does not match any file.

> 14 03 2017 08:54:27.266:WARN [watcher]: Pattern "C:/Temp/AureliaTest/scripts/app-bundle.js" does not match any file.

I understand that the bundles name should include a hash like `vendor-bundle-{hash}.js`, but what is the recommended approach to let karma know what the name of the bundle is? Should this be fixed with the `au build` or `au test` command? Or do I need to change my karma config by myself?

**Steps to reproduce:**
I updated to the newest Aurelia CLI (0.26.1) and created a new project with the following steps:

- App name : Test
- Custom setup
- Typescript
- Default template
- CSS processor: Sass
- Unit testing: Yes
- Default code editor: VS code
- Create the project: Yes
- Install dependencies: Yes

I enabled build revisions in the `aurelia.json`: http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/8

```
"options": {
  "minify": "stage & prod",
  "sourcemaps": "dev & stage",
  "rev": true
}
```
Aftwerwards I ran the build `(au build)` and ran the unit tests `(au test)`

This results in the following code sample: https://github.com/jimmyvdberg/aurelia-revisions-and-unit-tests and the warning messages shown above.

I also posted this question on Stack Overflow because I am not sure if this is a bug at all. You can find that question here: http://stackoverflow.com/questions/42781044/recommended-approach-for-combining-aurelia-build-revisions-and-unit-testing

**Expected/desired behavior:**

I expect that the build revisions will work without having to change the karma config by myself. So that the command `au test` will get the correct bundles.

**Comment by JeroenVinke** [comment]
@AStoker as soon as we've fixed https://github.com/aurelia/cli/issues/378 we could fix this one by using globs in karma to find the vendor-bundle (e.g. `scripts/vendor-bundle*.js`).

**Comment by AStoker** [comment]
I would recommend **not** running tests off of hashed code. If you want to test production code, test your code in `stage` mode (it's the same thing but without source maps). I don't think we could just use a glob route, because if you're already trying to run tests off of hashed code, that means you're running your dev code as hashed (again, I don't recommend it, I would recommend **not** leaving `"rev": true`, but rather `"rev": "prod"`). And if we have multiple hashed bundles (like you would if you're using `rev: true`), then a glob route would pick up all the bundles instead of the one desired.  

I would chalk this one up to how you set up your build environment. If you want to test hashed code, then you should either manually enter the hashed name (because we can't know that before time, unless you want to go off an entirely different path which _is_ valid, but quite different), or you use a glob route (like you recommended), but ensure that you only have one hashed file where you're looking.

**Comment by JeroenVinke** [comment]
I agree with @AStoker

**Comment by zedL** [comment]
I had the same issue. I solved it for me by changing the karma.conf.js and delete the created bundle files on each build.

karma.conf.js changes:
`
const scriptsFolder = './scripts/';
const fs = require('fs');

...

let appSrc = fs.readdirSync(scriptsFolder).filter(fn => (fn.startsWith('app-bundle') || fn.startsWith('vendor-bundle')) && !fn.endsWith('.map')).map(fn => path.join(output, fn));

console.log('appSrc', appSrc);

// configTarget from aurelia.json is vendor-bundle.js
// let entryIndex = appSrc.indexOf(path.join(output, project.build.loader.configTarget));
let entryIndex = appSrc.indexOf(appSrc.filter(f => f.includes('vendor-bundle'))[0]);

`

build.ts changes
`
import * as clean from './clean';

....

export default gulp.series(
  clean.deleteScripts, // added this one
  readProjectConfiguration,
  gulp.parallel(transpile, processMarkup, processCSS, copyFiles),
  writeBundles
);
`

clean.ts // my own clean up stuff
`
import * as gulp from 'gulp';
import * as del from 'del';

export default gulp.series(
  deleteScripts,
  deleteWwwRoot,
);

export function deleteScripts() {
  return del([
    './scripts/**/*.*',
    '!./scripts/modernizr-custom.js',
    '!./scripts/oidc-client.min.js',
    ], {dryRun: false}).then(paths => {
    console.log('Deleting following Files and folders:\n', paths.join('\n'));
  });
}
`
