### ISSUE TITLE
process global variable

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/cli#607]
**I'm submitting a feature request**

* **Library Version:**
0.28.0

**Please tell us about your environment:**
* **Operating System:**
Windows

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
When bundling a script such as [process-nextick-args](https://github.com/calvinmetcalf/process-nextick-args/blob/master/index.js) which uses the `process` global, bundling successfully completes, but in the browser it fails to execute claiming that `process` is undefined, which is true.

**Expected/desired behavior:**

Webpack does this nicely, by seemingly injecting a fake `process` global:

![img](https://files.gitter.im/JeroenVinke/3Wfv/blob)

![img](https://files.gitter.im/JeroenVinke/JtFd/blob)

* **What is the motivation / use case for changing the behavior?**
[processnextick-args](https://github.com/calvinmetcalf/process-nextick-args/blob/master/index.js) is a dependency of [readable-stream](https://github.com/nodejs/readable-stream) which is a dependency of [pouch-db](https://github.com/pouchdb/pouchdb)

**Comment by JeroenVinke** [comment]
probably need to do the same for `Buffer` and others defined in: https://github.com/webpack/node-libs-browser/tree/master/mock

**Comment by huochunpeng** [comment]
Latest cli does support node-libs-browser. It has imperfect support of globals "process" and "Buffer", as described in the doc. https://aurelia.io/docs/cli/cli-bundler/dependency-management#auto-tracing

**Comment by 3cp** [comment]
cli-bundler could not properly fix this due to the amodro-trace does zero scope analysis. We are not going to do major upgrade to cli-bundler because it's in maintenance mode for Aurelia 1 only.

In Aurelia 2, we dropped cli-bundler, replaced it with the successor [dumber](https://dumber.js.org) bundler. The new bundler solved this issue (plus few others) from ground up. Right now, we have webpack and bundler support for Aurelia 2, we are going to add support of Parcel 2 and FuseBox 4 when they were released.

Users can also use dumber with Aurelia 1 right now, there is skeleton provided in dumber repo https://github.com/dumberjs/new, just do `npx makes dumberjs`.
