### ISSUE TITLE
Scroll binding does not fire

### ISSUE THREAD

**Issue by YardGnomeNinja** [aurelia/cli#610]
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v7.4.0

* **NPM Version:**
4.0.5

* **Browser:**
Chrome 57.0.2987.133

* **Language:**
TypeScript 2.2

**Current behavior:**
Scroll binding does not fire.

**Expected/desired behavior:**
Scroll binding fires. (if it's even a feature at this point)

I've created a bare-bones example of what I'm trying to do based on the example here: [https://www.danyow.net/scroll-binding-with-aurelia/](https://www.danyow.net/scroll-binding-with-aurelia/). The only alterations I've made to the CLI generated code is in app.html and app.js. It is available here: [https://github.com/YardGnomeNinja/aurelia-scrollTest](https://github.com/YardGnomeNinja/aurelia-scrollTest).

I'm guessing it's not truly a bug and I'm just missing something, or perhaps scroll binding is no longer supported.

In the event this is still a valid feature, I'd also like to point out that searching the official documentation for "scroll" or "scroll binding" doesn't return results and as such the www.danyow.net link above and Stack Overflow appear to be the only source for this information.

**Comment by AStoker** [comment]
@YardGnomeNinja, I'm going to close this for now since it's not an issue with the CLI.
For your issue in particular, it's probably not firing because you're not scrolling in the `<div>`. Your binding is on the div itself, but without the appropriate classes, you're scrolling on the window, not the div. Take a look at the `styles.css` inside the original gist (https://gist.run/?id=f5b43de0086cddc254ce) to see how you can make the div itself scrollable. 
If this doesn't solve the issue, feel free to ask the question on Gitter (tons of people there to help), or post the issue on Stack Overflow (feel free to post the link to the question here so I can help out).

Thanks for taking time to try out Aurelia and being willing to help us make it better :)

**Comment by YardGnomeNinja** [comment]
Thanks! It obviously didn't occur to me that this was a styling issue. I see now that simply making the div:
`<div style="position: absolute; top: 0px; left: 0px; bottom: 0px; right: 0px; overflow: auto;" scroll.trigger="handleScrollEvent($event)">` made it work.

**Comment by AStoker** [comment]
Glad you got it working :)
