### ISSUE TITLE
au aborts Windows batch execution

### ISSUE THREAD

**Issue by bmarotta** [aurelia/cli#618]
**I'm submitting a bug report**

* **Library Version:**
0.27.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.2.3

* **NPM Version:**
3.10.10

* **Browser:**
N/A

* **Language:**
TypeScript 2.3.1

**Current behavior:**
The au command will abort any Windows batch execution. The problem can be reproduced by creating a 2 lines batch file:

```
au build
echo Finished
```

The second line will not be executed. This prevents the automation of a build + deploy batch.

**Expected/desired behavior:**
The subsequent lines should be executed

**Comment by JeroenVinke** [comment]
I'm not sure why, but I get the same result with any globally installed node module:
```
gulp -v
echo Finished
```

does not echo "Finished" either

This works for me though:
```
call au.cmd build
echo Finished
```

as well as
```
node .\node_modules\aurelia-cli\bin\aurelia-cli.js build
echo Finished
```

**Comment by AStoker** [comment]
I experienced this after upgrading from 0.26.0 as well (currently happening on 0.28.0). 
So I'm thinking something has changed, just not sure what yet. @bmarotta, I'd appreciate you helping me out digging in to what's happening. I got something else on my plate with a fast approaching deadline, but then I plan on tackling this.

**Comment by ghidello** [comment]
Globally installed modules are  batch files (with a `.cmd` extension) and, as far as I remember, when you invoke the batch program **a** from another batch the execution flow will stop at the end of **a** unless you prepended it with the keyword **call**. 
The command `node .\node_modules\aurelia-cli\bin\aurelia-cli.js build` works, in a batch file, because it is a real executable.
So, my rule of thumb is to always **call** a batch from another batch and see what happens: I remember that there are a number of edge cases but, so far, I never hit one.

**Comment by JeroenVinke** [comment]
@ghidello Thank you, that does make a lot of sense

**Comment by AStoker** [comment]
Can we mark this as closed given the case Ghidello gave? @bmarotta, does that work for you?

**Comment by bmarotta** [comment]
Fine for me
