### ISSUE TITLE
Integrate command-plugin with the .aurelia directory

### ISSUE THREAD

**Issue by joelcoxokc** [aurelia/cli#64]
Once @PWKad merges his plugin command, Allow the command to install into the .aurelia directory. 

Create API/ gulp tasks for watching this directory and moving changes to jspm_packages

**Comment by joelcoxokc** [comment]
@PWKad What are your thoughts about implementing this. I know it is a brief description. I will discuss later in depth.

**Comment by ahmedshuhel** [comment]
@EisenbergEffect @PWKad @zewa666  @joelcoxokc  If I am not mistaken, [jspm link](https://github.com/jspm/jspm-cli/wiki/Linking) is intended to perform this kind of tasks. So, If we want to handle this with `cli`, wouldn't it be better if we just use `jspm   api` behind instead of creating `.areliafolder` and gulp task and then copy changes to jspm_packages?

**Comment by joelcoxokc** [comment]
That is the idea

**Comment by EisenbergEffect** [comment]
Deprecated cli.
