### ISSUE TITLE
Disabling/enabling minification from aurelia.json

### ISSUE THREAD

**Issue by tdamir** [aurelia/cli#652]
**I'm submitting a feature request**

**Current behavior:**
Case1: When we create the new project with au new and choose to use minification, it works as expected - the aurelia.json markupProcessor is set up according to that and process-markup.ts contains the code for using the minification. If we change the minification setting from 'minimum' to 'none', it is reasonable for one to expect that minification will be disabled, but that is not the case. To disable the minification we have to modify the process-markup.ts file which is a little bit illogical in my humble opinion.

Case2: If project is created without minification, in aurelia.json the none will be set in markupProcessor section. Again if we would like to enable the minification, we have to modify aurelia.json and process-markup.ts files.

**Expected/desired behavior:**
We should universally be able to control minification by modifying only the aurelia.json file.

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @tdamir ?

**Comment by Alexander-Taran** [comment]
@3cp I think it is implemented

**Comment by 3cp** [comment]
This request is talking about using the `"minify": "stage & prod",` option from aurelia.json to control the behaviour of gulp-htmlmin in `process-markup.js`

Unfortunately, that "minify" option only controls js minify, and it's difficult to be used in other place. The reason is that the option supports kind of mini expression which is only resolved inside aurelia-cli, and we didn't expose the api to evaluate the option expression to a final boolean value.

The accessor of cli-bunlder, the [dumber bundler](https://dumber.js.org) doesn't handle minify at all. It's left to the user to use gulp-terser to minify js files. So that user can use same logic in gulpfile to control both gulp-terser and gulp-htmlmin.

**Comment by 3cp** [comment]
Actually there is a way to access the api. There are some example in transpile task.

```js
import project from '../aurelia.json';
import { CLIOptions, Configuration } from 'aurelia-cli';
const buildOptions = new Configuration(project.build.options);
const minify = buildOptions.isApplicable('minify');
```

Then you can control gulp-htmlmin with gulp-if

```
.pipe(gulpIf(minify, htmlmin({...}))
```

I will add it to the skeleton.
