### ISSUE TITLE
[bug] Unable to resolve internal dependency in imported library

### ISSUE THREAD

**Issue by justindra** [aurelia/cli#690]
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch)

* **Node Version:**
6.11.1

* **NPM Version:**
3.10.10

* **Browser:**
all

* **Language:**
TypeScript 2.4

**Current behavior:**
Adding [auth0](https://www.npmjs.com/package/auth0-js) library does not resolve the internal dependency of the library itself.

Coming up with these errors when running `au run --watch`

```bash
 ------- File not found or not accessible ------
| Location: /home/justin/projects/my-proj/node_modules/auth0-js/src/authentication.js
| Requested by: /home/justin/projects/my-proj/src/components/login/index.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
 ------- File not found or not accessible ------
| Location: /home/justin/projects/my-proj/node_modules/auth0-js/src/management.js
| Requested by: /home/justin/projects/my-proj/src/components/login/index.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
 ------- File not found or not accessible ------
| Location: /home/justin/projects/my-proj/node_modules/auth0-js/src/web-auth.js
| Requested by: /home/justin/projects/my-proj/src/components/login/index.js
| Is this a package? Make sure that it is configured in aurelia.json and that it is not a Node.js package
 -----------------------------------------------
```

`aurelia.json` file dependencies as below
```
dependencies:
   {
        "name": "auth0-js",
         "main": "src/index.js",
         "path": "../node_modules/auth0-js"
   }
```

**Expected/desired behavior:**

It should resolve those files properly and not use the default project root folder to find it.

* **What is the motivation / use case for changing the behavior?**
So anyone can add libraries that has its own internal dependencies using the aurelia cli

**Comment by JeroenVinke** [comment]
Hey @justindra,

Instead of using the src directory you should use the transpiled code, which auth0 puts in the `build` directory, like [this](https://github.com/JeroenVinke/aurelia-cli-auth0/blob/master/aurelia_project/aurelia.json#L76-L80).

Take a look at [this project](https://github.com/JeroenVinke/aurelia-cli-auth0/). Let me know if you have any more issues.

**Comment by man0790** [comment]
Hi there, I am getting the same error. I am trying to read json file . Could you please tell me how to resolve this?

**Comment by 3cp** [comment]
@man0790 This issue is for outdated cli bundler. Your error should be different unless you are running an outdated aurelia-cli (before v1.0.0).

If you are running outdated cli, `npm i -g aurelia-cli` to upgrade the global installed cli to latest, then try `au new` to create new app. For an existing app, upgrade it to latest cli carefully following https://aurelia.io/docs/cli/migrating#upgrade-to-auto-tracing-bundler-100-beta1-or-above

If you are experiencing a bug or issue with latest cli, fire a new GitHub issue with details of your problem. Thanks!
