### ISSUE TITLE
Success using Nightmare with Jest in the Aurelia CLI for E2E Testing!!

### ISSUE THREAD

**Issue by ajoslin103** [aurelia/cli#795]
I couldn't get Protractor running with the Aurelia CLI -- but Nightmare.js stepped up to the plate nicely

I open this as an issue so that the Aurelia team will know what I found, feel free to close it and pass it to the appropriate people.  

#1 yarn add --dev nightmare

#2 create a file: test/e2e/nightmare.spec.js
```
import nightmare from 'nightmare';
describe('When starting the app', function () {
	test('it shows out of service', async function () {
		let page = nightmare({
			show: true,
			dock: true,
			openDevTools: {
				mode: 'detach'
			}
		}).goto('http://localhost:8080');
		let text = await page.evaluate(() => document.body.textContent)
			.wait(3000)
			.end();
		expect(text).toContain('out of service');
	});
});
```
#3 au run --watch 

#4 au jest (in a different session)

The gorgeous result: a window opens showing the out-of-service page, another opens showing the dev console, then jest passes the test, and nightmare waits 3 seconds before closing up and everything shuts down.

**Comment by zewa666** [comment]
Just for the sake of completeness I'll post the link to how you can setup Protractor with the Aurelia CLI. http://pragmatic-coder.net/setup-protractor-e2e-tests-with-aurelia-cli-apps/

As for your case it didn't work because you've been using Aurelia CLI with Webpack, which uses Jest as the test runner. Now Protractor is heavily tied to Karma/Jasmine which is the reason it didn't run that smooth.

Keep in mind though that actually E2E tests aren't related to your apps code, as such even in the Webpack scenario you would have been able to add jasmine and karma for E2E testing, although using webpack/jest.

I'm gonna close this issue for now as I don't expect the CLI to ever provide any E2E scenario out of the box, due to the vast amount of options, but definitely thanks for looking into that.

**Comment by ajoslin103** [comment]
Yes I had seen that post, but it didn't work for me this time - my previous experience had been with the webpack skeleton where I executed 'WEBPACK_PORT=19876 npm start' in one session and then 'npm run e2e:start'  in another.  Whereas this time I am all 'au' all the way, loving it and modifying the tasks as needed (see discourse topics with 'solved:' prefixes) to adjust for this projects' odd requirements.  But attempting 'WEBPACK_PORT=19876 au run' did not run on the right port and even tho I found 'npm run start e2e' to launch nothing would connect.  Stuck.

I use the e2e in conjunction with remark.js to create a standalone interactive slideshow of the product's screens, dialogs and workflows -- and being able to re-run the e2e whenever the boss want's an updated set of screenshots has been a huge time-saver.  

I was hoping that the CLI could add a little trickiness into the jest.js task to launch the app and then run au jest in another session if it detected e2e specs and nightmare installed.  Perhaps having a simple template e2e spec with a comment saying that installing nightmare would enable it.
