### ISSUE TITLE
Can't set NODE_ENV for redux based plugins

### ISSUE THREAD

**Issue by alexsaare** [aurelia/cli#798]
**I'm submitting a feature request**

* **Library Version:**
0.32.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.6.0

* **NPM Version:**
3.10.3

* **Browser:**
all 

* **Language:**
all 

* **Loader/bundler:**
RequireJS

**Current behavior:**
Error in the console of deployed application

You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.

* **What is the expected behavior?**
Need to be able to set process.env.NODE_ENV = JSON.stringify('production')  

* **What is the motivation / use case for changing the behavior?**
See here for extensive discussion on angular cli - https://github.com/angular/angular-cli/issues/2110 

We need to be able to to the same.  

Creating a production.js environment config doesn't work as it needs to be _"production".js_ which is an invalid file name.

**Comment by JeroenVinke** [comment]
Hi, thanks for opening up the issue report. Could you perhaps put together a new app that has this problem?

**Comment by Alexander-Taran** [comment]
...Shooting range...
- we have a problem with this new weapon. It does not hit the target!!!
- well.. the bullet left the barrel successfully. The problem is with the target.

can be closed I guess

**Comment by Alexander-Taran** [comment]
@3cp thee consecutive pings (-:

**Comment by 3cp** [comment]
Cli uses its own env, but also respect NODE_ENV

When NODE_ENV is production, cli env will be set to prod. Same treatment happens for development to dev.

But unfortunately even if you replace

    au build --env prod

With (use cross-env if win32 support is needed)

    env NODE_ENV=production au build

It still would not work as expected, because cli bundler doesn't stub process.env.NODE_ENV for js code to inspect env at runtime. Other bundlers do.

The successor of cli-bundler, [dumber bundler](https://dumber.js.org/node-env) does it.
