### ISSUE TITLE
Separate Library and CLI

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/cli#8]
All functionality of the cli should be in a separate library. The cli should just automate this library. This would allow the library to be used directly inside of gulp or any other node-based tool.

Perhaps `aurelia-tools` is the best repo to move the core functionality into?

**Comment by ahmedshuhel** [comment]
Rather than a single separate library could we consider multiple smaller focused libraries? CLI houses different functionalities with different purposes. Let's take `bundling` and `scaffolding` for example. They are very different in nature. So it's probably make more sense to factor them out into two separate libs. 

The modules in the CLI are not very mature yet. So we should probably wait a little more before refactorig.

**Comment by EisenbergEffect** [comment]
Sounds fantastic. Keep working in the current repo and let's just keep this in mind. When things mature, we will talk about how they should be split apart. We'll leave this issue open as a reminder of that.

**Comment by joelcoxokc** [comment]
I have some solutions to this issue, I will be making a pull request soon on.

**Comment by joelcoxokc** [comment]
One of the issues we have is that our commander logic is in the same file that will be required on the library side. I have pulled all the commander logic from the index.js. and placed it into a file called interface.js I figured this would be a valid name, as it is the command line interface.

**Comment by joelcoxokc** [comment]
We also should be exporting an instance from the index file, rather than the constructor. Otherwise, it will be difficult to re access the instance if not stored properly. 

Should I make this another issue?
