### ISSUE TITLE
Removable favicon in root folder

### ISSUE THREAD

**Issue by LittleGnome** [aurelia/cli#828]
Hello,

When I create a Aurelia app with the newest version of the CLI, there is a favicon.ico in the root folder and in the static folder.

If I'm right the favicon.ico in the root folder can be removed. The favicon.ico is copies/bundled via CopyWebpack.

Greetings,

Little Gnome

**Comment by huochunpeng** [comment]
@Alexander-Taran since I am not a webpack user, I can only guess the default setup is asking user to put all customised static resources (including `favicon.ico`) in `static/` folder, then update `webpack.config.js` to copy them into desired places.

Seems nothing wrong to me. BTW, as the root favicon is regenerated by webpack, you can just add it in `.gitignore`.
