### ISSUE TITLE
Update to babel 7 ?

### ISSUE THREAD

**Issue by Jule-** [aurelia/cli#846]
Is there any plan to update `aurelia-cli` to `babel` 7 soon?

It seems that these 2 requires messed transpilation when we want to use new `babel` version:
https://github.com/aurelia/cli/blob/15b1f1f6d4ee74a5a429ca90651d61b0e8d8abdf/lib/project.js#L207-L218

And it seems that this transformation do the trick:
```javascript
function installBabel() {
  require('@babel/polyfill');
  require('@babel/register')({
    plugins: [
      '@babel/plugin-transform-modules-commonjs'
    ],
    ignore: [(filename) => {
      let relativeFromProjectRoot = path.relative(this.directory, filename);
      return !/^aurelia_project/.test(relativeFromProjectRoot);
    }]
  });
}
```

This will allow us to use improvements of [`@babel/preset-env`](https://github.com/babel/babel/tree/master/packages/babel-preset-env) in a local `.babelrc` file.

**Comment by Alexander-Taran** [comment]
Would you like to provide a pull request for it @Jule- ?

**Comment by Jule-** [comment]
Yes if nothing is already planned. Maybe tomorrow.

**Comment by arabsight** [comment]
babel 7 is still in beta

**Comment by Jule-** [comment]
Indeed but at least I want to migrate to new babel repo (`@babel/*`), removing warnings, and maybe wait for the release before switching to `babel` 7?

**Comment by bigopon** [comment]
Babel 7 has several upgrades, regard to spec changes. One of that is the decorator proposal spec upgrade. Aurelia current decorator implementation is based on old version of that, and probably won't work well together with Babel 7. I'm not sure what our strategy towards this change is @EisenbergEffect

**Comment by EisenbergEffect** [comment]
A couple of weeks ago there was a meeting with Yahuda, who is working on the decorators spec, and the major framework leaders. I'm completely up to speed about where decorators is at now :) The new spec looks very good and is poised to move into stage 3. At that point, we'll probably see transpiler and polyfill implementations. During that meeting we also talked about compatibility layers for transpiler migration. I think we'll probably wait for that to happen before we make any moves. Otherwise, it's a major breaking change to update our implementations. For vNext we can start from day 1 with the new spec.

**Comment by aicokleinovink** [comment]
So yesterday I wanted to upgrade to Babel 7 (because of Typescript support), but if I'm correct that won't work at the moment?? Because of the decorators getting transpiled differently?

**Comment by arabsight** [comment]
you can use the legacy option with the new plugin, and if you're using class-properties then the decorators plugin must come before class-properties pluginn and the later must must use loose mode:
```
const plugins = [
  ['@babel/plugin-proposal-decorators', { legacy: true }],
  ['@babel/plugin-proposal-class-properties', { loose: true }]
];
```
