### ISSUE TITLE
output setting for webpack/ts scaffold mismatch with .gitignore excludes

### ISSUE THREAD

**Issue by Alexander-Taran** [aurelia/cli#854]
**I'm submitting a bug report**

* **Library Version:**
0.33.1

* **Language:**
 TypeScript 

* **Loader/bundler:**
Webpack 

**Current behavior:**
scaffolded project with webpack/typescript has output set as 'dist'
.gitignore has exclude for scripts

.gitignore also does not have exclude for `coverage-jest`

* **What is the expected behavior?**
.gitignore has exclude for dist specified
or output is set for scripts
whatever makes more sense

* **What is the motivation / use case for changing the behavior?**
keeping git repos fit

let's decide on which path to chose and I'll make a PR

**Comment by fkleuver** [comment]
There's no question `scripts` should go because that's aurelia-cli only. Webpack doesn't write there.

I think for apps that are not plugins, it's typically better to have the `dist` in gitignore. Contents in the folder behave much like a cache - it keeps changing, and the changes are large. You typically publish to another location anyway.

**Comment by Alexander-Taran** [comment]
@fkleuver are you stalking me? (-:

**Comment by fkleuver** [comment]
I'm stalking whatever pops up in the gitter feed. Can't help it that that's all you :)

**Comment by michaelw85** [comment]
karma coverage should also be added to the gitignore.
