### ISSUE TITLE
To support vNext "view!" requirejs plugin

### ISSUE THREAD

**Issue by 3cp** [aurelia/cli#916]
Task for aurelia/aurelia#112

**Comment by fkleuver** [comment]
Yesplz

**Comment by huochunpeng** [comment]
The cli needs to be redesigned to support vNext "view!" plugin.

Current cli is designed based on vCurrent convention. All html and css files are packed based on assumption that they will be consumed by text plugin `"text!foo.html"` (`"text!foo.css"`). That's why the text plugin applies to all files with file extension `.html` and `.css`, without consulting module tracing.

With vNext, all deps are explicitly tracable. We need to distinguish between `"text!foo.html"` and `"view!foo.html"`. Hence we cannot solely rely on the file extension to make decision of applying plugin, but have to bundle html/css resources based on explicit deps tracing.

Most of auto-tracing cli, and aurelia-webpack-plugin, is to teach the bundler about vCurrent convention. All of them will become obsolete with vNext.

I think we should take the opportunity to design vNext-cli, instead of patching current one. There are few things we can simplify. One of them is the gulp task files, which I talked with @JeroenVinke before, we could rewrite tasks in just commonjs code, instead of esnext/ts, so we can (1) cut of dependencies on babel-register and typescript, (2) only maintain one version of tasks instead of two (esnext and ts). We cannot do this to current cli, because dropping dependency will break tasks of existing user apps.

**Comment by 3cp** [comment]
"view!" has been removed from Aurelia 2.
